application: surveysamplesize
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: samplesize.application

libraries:
- name: webapp2
  version: latest